const stickers = [
  {
    _id: '1',
    name: 'Keep Calm',
    image: '/images/calm.png',
    price: 1.99,
    countInStock: 100,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Coffee & Cigaret',
    image: '/images/cigar.png',
    price: 1.99,
    countInStock: 90,
    rating: 4,
    numReviews: 15,
  },
  {
    _id: '3',
    name: 'Coffee Break',
    image: '/images/coffee.png',
    price: 2.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Best Dad in the Galaxy',
    image: '/images/dad.png',
    price: 3.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Offline Monster',
    image: '/images/dainasor.png',
    price: 4.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'I Code in the Dark',
    image: '/images/dark.png',
    price: 2.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'FullSnack Developer',
    image: '/images/fullsnack.png',
    price: 2.99,
    countInStock: 10,
    rating: 4,
    numReviews: 18,
  },
  {
    _id: '8',
    name: 'Geek Lego',
    image: '/images/Geek.png',
    price: 2.99,
    countInStock: 40,
    rating: 4.5,
    numReviews: 1,
  },
  {
    _id: '9',
    name: 'JavaScript',
    image: '/images/js.png',
    price: 4.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 22,
  },
  {
    _id: '10',
    name: 'I am a Lazy ProGrammer',
    image: '/images/lazy.jpg',
    price: 5.99,
    countInStock: 88,
    rating: 4.2,
    numReviews: 32,
  },
  {
    _id: '11',
    name: 'Legacy Code',
    image: '/images/legacy.jpg',
    price: 1.99,
    countInStock: 8,
    rating: 4.1,
    numReviews: 15,
  },
  {
    _id: '12',
    name: 'There is no Place like',
    image: '/images/localhome.jpg',
    price: 5.99,
    countInStock: 22,
    rating: 3.9,
    numReviews: 32,
  },
  {
    _id: '13',
    name: 'Metalica',
    image: '/images/metalica.png',
    price: 1.99,
    countInStock: 0,
    rating: 4.3,
    numReviews: 19,
  },
  {
    _id: '14',
    name: 'Nasa Nerd',
    image: '/images/nerd.png',
    price: 6.99,
    countInStock: 15,
    rating: 4.6,
    numReviews: 52,
  },
  {
    _id: '15',
    name: 'Nerd Life',
    image: '/images/nerdlife.png',
    price: 0.99,
    countInStock: 8,
    rating: 4,
    numReviews: 16,
  },
  {
    _id: '16',
    name: 'No Coffee No Code',
    image: '/images/nocoffe.png',
    price: 2.99,
    countInStock: 0,
    rating: 4.1,
    numReviews: 1,
  },
  {
    _id: '17',
    name: 'Node JS',
    image: '/images/nodejs.png',
    price: 3.99,
    countInStock: 30,
    rating: 4,
    numReviews: 92,
  },
  {
    _id: '18',
    name: 'SEMICOLON',
    image: '/images/semicolon.png',
    price: 3.99,
    countInStock: 30,
    rating: 4.2,
    numReviews: 55,
  },
  {
    _id: '19',
    name: 'It Works',
    image: '/images/works.png',
    price: 3.99,
    countInStock: 20,
    rating: 4.6,
    numReviews: 45,
  },
];

export default products;
