export const STICKER_LIST_REQUEST = 'STICKER_LIST_REQUEST';
export const STICKER_LIST_SUCCESS = 'STICKER_LIST_SUCCESS';
export const STICKER_LIST_FAIL = 'STICKER_LIST_FAIL';

export const STICKER_DETAILS_REQUEST = 'STICKER_DETAILS_REQUEST';
export const STICKER_DETAILS_SUCCESS = 'STICKER_DETAILS_SUCCESS';
export const STICKER_DETAILS_FAIL = 'STICKER_DETAILS_FAIL';

export const STICKER_DELETE_REQUEST = 'STICKER_DELETE_REQUEST';
export const STICKER_DELETE_SUCCESS = 'STICKER_DELETE_SUCCESS';
export const STICKER_DELETE_FAIL = 'STICKER_DELETE_FAIL';

export const STICKER_CREATE_REQUEST = 'STICKER_CREATE_REQUEST';
export const STICKER_CREATE_SUCCESS = 'STICKER_CREATE_SUCCESS';
export const STICKER_CREATE_FAIL = 'STICKER_CREATE_FAIL';
export const STICKER_CREATE_RESET = 'STICKER_CREATE_RESET';

export const STICKER_UPDATE_REQUEST = 'STICKER_UPDATE_REQUEST';
export const STICKER_UPDATE_SUCCESS = 'STICKER_UPDATE_SUCCESS';
export const STICKER_UPDATE_FAIL = 'STICKER_UPDATE_FAIL';
export const STICKER_UPDATE_RESET = 'STICKER_UPDATE_RESET';

export const STICKER_CREATE_REVIEW_REQUEST = 'STICKER_CREATE_REVIEW_REQUEST';
export const STICKER_CREATE_REVIEW_SUCCESS = 'STICKER_CREATE_REVIEW_SUCCESS';
export const STICKER_CREATE_REVIEW_FAIL = 'STICKER_CREATE_REVIEW_FAIL';
export const STICKER_CREATE_REVIEW_RESET = 'STICKER_CREATE_REVIEW_RESET';

export const STICKER_TOP_REQUEST = 'STICKER_TOP_REQUEST';
export const STICKER_TOP_SUCCESS = 'STICKER_TOP_SUCCESS';
export const STICKER_TOP_FAIL = 'STICKER_TOP_FAIL';
